### ISSUE TITLE
Can you bundle this to an alfred workflow?

### ISSUE THREAD

**Issue by muuvmuuv** [klaascuvelier/alfred-mdn#12]
I don't want to install ALfred Workflows through package managers because I have NVM and this is nothing I want in every version.

**Comment by klaascuvelier** [comment]
Hi @muuvmuuv I'll try to look into that.

**Comment by klaascuvelier** [comment]
@muuvmuuv quickly added the current version of the plugin to the repo: https://github.com/klaascuvelier/alfred-mdn/blob/master/alfred-mdn.alfredworkflow

Will look into adding doing this automatically when releasing.
I'll keep this issue open but at least you should be able to install now.

**Comment by muuvmuuv** [comment]
Yes, thanks!
