### ISSUE TITLE
Workflow doesn't work anymore

### ISSUE THREAD

**Issue by ericloong90** [klaascuvelier/alfred-mdn#14]
Workflow has stopped working since a couple of weeks ago. Initially thought the MDN site is down or something, but it has been like this for the past couple of weeks. 

The following is the Alfred error that I got from running the `mdn` command.

TypeError: Cannot read property 'replace' of undefined
    at stripHtml (/usr/local/lib/node_modules/alfred-mdn/index.js:37:17)
    at /usr/local/lib/node_modules/alfred-mdn/index.js:10:26
    at Array.map (<anonymous>)
    at /usr/local/lib/node_modules/alfred-mdn/index.js:8:35

Reinstalling and updating the extension doesn't seem to fix it as well.

Currently running Node v14.15.4

**Comment by klaascuvelier** [comment]
Tanks for bringing this to my attention. I will investigate this and publish a fix ASAP

**Comment by klaascuvelier** [comment]
Hey @ericloong90, I published version 2.1.5 which should fix the issue.
Looked like MDN updated the structure of their response,.
