### ISSUE TITLE
Library not loaded error

### ISSUE THREAD

**Issue by Fadarrizz** [klaascuvelier/alfred-mdn#17]
Hi there,

The workflow doesn't seem to be working because of a library that isn't loaded:

![image](https://user-images.githubusercontent.com/22003779/117112142-ea1f2800-ad88-11eb-9d84-5a3da6ca3fa6.png)

Reinstalling didn't work, unfortunately.

**Comment by klaascuvelier** [comment]
Hi @Fadarrizz this looks like a Node issue to me.
Are you experiencing any other issues with Node, and/or did you recently upgrade/change your node version?

**Comment by klaascuvelier** [comment]
There seem to be quite some similar reports on the internet, here's one with a possible solution: https://stackoverflow.com/a/54873233/1083240

I'll close this issue already as it's not related to my workflow.

**Comment by Fadarrizz** [comment]
Thanks @klaascuvelier! I hope a brew cleanup or update will fix the problem, thanks for the SO post!
