### ISSUE TITLE
Workflow stopped working?

### ISSUE THREAD

**Issue by dmitry-ivanov** [klaascuvelier/alfred-mdn#22]
Hi,

Thank you for creating and maintaining the workflow!

It seems that it stopped working recently:

![mdn](https://user-images.githubusercontent.com/1286821/179224987-0744d25d-e07b-4c08-8927-41f9d28ac556.jpg)

Could you please take a look?

Thank you!

**Comment by kiliman** [comment]
MDN changed the API URL. For a quickfix, right-click on the `mdn` workflow and select _Open in Finder_.

Edit the *index.js* file.

Change the URL to `${mdnDocBase}/api/v1/search?q=${alfy.input}`

Save. Your workflow should work now.

**Comment by klaascuvelier** [comment]
Thanks for reporting @dmitry-ivanov and thank you very much @kiliman for the workaround and the PR with the fix #23 .
I just published a new version `alfred-mdn@2.1.6`.

**Comment by dmitry-ivanov** [comment]
@kiliman @klaascuvelier Thank you!

@klaascuvelier Could you please also publish the `.alfredworkflow` file _(to make it possible to install directly to Alfred, instead of npm globally)_?

_PS: As a suggestion - would be really cool to introduce [self-updates](https://alfred-workflow.readthedocs.io/en/latest/user-manual/update.html), if you have time for that._

**Comment by klaascuvelier** [comment]
@dmitry-ivanov I updated the workflow flow, can you check if it works alright?

Thanks for suggesting self-updates, I'll look into this. No promises on a timeline though ;)

**Comment by dmitry-ivanov** [comment]
@klaascuvelier It works, thank you! 👍

_PS: Maybe it's also worth creating a new [release](https://github.com/klaascuvelier/alfred-mdn/releases) (similarly to `2.1.5`)?_

_I think that might be more transparent for other users._

_Thanks again!_

**Comment by klaascuvelier** [comment]
Yep, good point. I will look into smoothening my release process (automating stuff) asap.
I have to do all of this manually now which makes me forget things.
