### ISSUE TITLE
ParseError: Unexpected token < in JSON at position 3

### ISSUE THREAD

**Issue by peterschussheim** [klaascuvelier/alfred-mdn#4]
Hi Klaas,

Great alfred extension!  I use this many times daily and just now received an error whenever I trigger a search:

```json
ParseError: Unexpected token < in JSON at position 3 in "https://developer.mozilla.org/en-US/search.json?q=h": 
<!DOCTYPE html>
<html lang="en-US" dir="ltr" class="no-js">
<head prefix="...
    at stream.catch.then.data (/Users/peter/.nvm/versions/node/v12.4.0/lib/node_modules/alfred-mdn/node_modules/got/index.js:118:14)
```

Any idea how to resolve this?

Thanks

### version info:
mdn 1.0.2
Alfred 4.0.3
darwin x64 18.7.0

**Comment by klaascuvelier** [comment]
Hey @peterschussheim sorry for my late response.
Did you find out what went wrong?
