### ISSUE TITLE
latest update always gives same results

### ISSUE THREAD

**Issue by mesqueeb** [klaascuvelier/alfred-mdn#6]
I just updated to the latest version:
<img width="663" alt="image" src="https://user-images.githubusercontent.com/3253920/66999548-322c1a80-f111-11e9-89c0-f459bf8bfea5.png">

But now I always get these results no matter what I type in:
<img width="567" alt="image" src="https://user-images.githubusercontent.com/3253920/66999417-ee391580-f110-11e9-954b-37473fc032ba.png">

**Comment by mesqueeb** [comment]
Nice! Laat maar weten!
Dees is echt een zalige plugin van een mede belg. 😉

**Comment by peterschussheim** [comment]
I see there is an open [issue](https://github.com/mdn/kuma/issues/5957) in the kuma repo but no response yet.  @klaascuvelier do you know if mdn has an official page that documents the search endpoints?  Perhaps we can modify your alfred script so the user can configure a search URL via Alfred preferences.
