### ISSUE TITLE
ReferenceError: results is not defined

### ISSUE THREAD

**Issue by mesqueeb** [klaascuvelier/alfred-mdn#8]
@klaascuvelier Now I'm getting this on the last version:
Not sure if it's related to #6
```
ReferenceError: results is not defined
    at /usr/local/lib/node_modules/alfred-mdn/index.js:9:23
```

-
mdn 2.0.2
Alfred 4.0.5
darwin 19.0.0

**Comment by mesqueeb** [comment]
https://github.com/klaascuvelier/alfred-mdn/blob/master/index.js#L9
maybe this line should check if results is an array before trying to do `.map`

**Comment by klaascuvelier** [comment]
Yeah, I can add resilience there, but this will only nicely handle errors, does not explain why you don't have results.
Double of #7 btw. Going to close this one
